# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 00:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journal',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 7, 1, 0, 34, 2, 675172, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
