# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journal_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='image',
            new_name='badge',
        ),
    ]
