# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20170624_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='badge_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journal',
            name='badge_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='journal',
            name='badge',
            field=models.ImageField(blank=True, height_field='badge_height', null=True, upload_to='', width_field='badge_width'),
        ),
    ]
