# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 20:38
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20170701_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
