# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20170624_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='badge',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
