# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_auto_20170624_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='badge_height',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='badge_width',
        ),
    ]
