# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 16:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardeners', '0002_auto_20170805_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='following',
            options={'verbose_name_plural': 'Following'},
        ),
        migrations.RemoveField(
            model_name='following',
            name='following',
        ),
        migrations.AlterField(
            model_name='following',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
