# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 16:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gardeners', '0003_auto_20170805_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='following',
            name='following',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
